### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by A2va** [andi23rosca/andi.dev#1]
Hi! I noticed your article on your blog about how you made your website, which I found really useful. And I'd like to use some of your vite plugins in my codebase, but neither your repo nor individual vite plugin files are licensed under an open source licence.

**Comment by andi23rosca** [comment]
Hey, i'm not sure how to add separate licenses for the content vs the code so I've not added a license to this repo yet

Feel free to use any of the code, including the plugins, components, and the overall css design/structure.
Only thing that's not for copying is the content itself (the posts, any images/illustrations I might add, etc)

👍🏻
